### ISSUE TITLE
Check mark cutoff on backup keys screen

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#101]
<img width="285" alt="Screen Shot 2021-05-25 at 2 57 44 AM" src="https://user-images.githubusercontent.com/3769672/119453096-10d7db00-bd05-11eb-9bfb-0b94564bbace.png">

**Comment by ricardobrg** [comment]
Could not reproduce that neither in 320px or 1440px wide screens.
![image](https://user-images.githubusercontent.com/8357343/119514307-47d0df80-bd4b-11eb-92b6-a62658728082.png)
![image](https://user-images.githubusercontent.com/8357343/119514378-5a4b1900-bd4b-11eb-96c3-5d9731a429b5.png)
