### ISSUE TITLE
Terms of Service is hidden on some phones

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#106]
![image](https://user-images.githubusercontent.com/3769672/119602136-851f8680-bdb8-11eb-8029-77c8b15d6a57.png)

**Comment by ricardobrg** [comment]
I have tested here and the scrolling is working... user can scroll up to see it.
![Screenshot_1622039090](https://user-images.githubusercontent.com/8357343/119677540-2fc59280-be15-11eb-91b2-292b0e90df3d.png)

**Comment by ricardobrg** [comment]
#175
