### ISSUE TITLE
Pineapple covers text

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#111]
![image](https://user-images.githubusercontent.com/3769672/119669802-56c89800-be06-11eb-8b21-b9dac2b9019f.png)

remove or redesign screen

**Comment by ricardobrg** [comment]
We have some quick fix options for it :

1 Remove the pineapple
2 change the text color
3 add brackground to text

**Comment by Prakhilm** [comment]
Add background

**Comment by annastoilova** [comment]
Done
