### ISSUE TITLE
Able to log in with an expired link

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#116]
Type your email open a expired link with tiki not browser then restart app you will be logged in even the link is expired
Note: the expired link need to be from the same email you have typed

**Comment by mike-audi** [comment]
First log in, then clear app data. Then attempt. 

other variants:
type your email click back button(including device back button) then restart app then you will be logged in
type your email open a referral link restart app and you get logged in
type your email restart app type your email and restart app again and you will be logged in

**Comment by ricardobrg** [comment]
#175
