### ISSUE TITLE
GO TO INBOX on certain phones is confusing

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#12]
This button can sometimes act odd, not opening the default email client. Either change the language & remove the button to have the user open their own email inbox or if possible fix it so the default open works correctly. 

To reproduce on iOS delete the default mail app. Android TBD

iOS
![image](https://user-images.githubusercontent.com/3769672/113085419-bf501b80-91ad-11eb-9dfe-c79434143f49.png)

Android
![Screenshot_20210330-064151_Email](https://user-images.githubusercontent.com/3769672/113085614-2cfc4780-91ae-11eb-8604-2c4468534b18.jpg)

**Comment by mike-audi** [comment]
waiting on design from @annastoilova. does not look realistic to fix in code. there is too much user/phone variation, some people don't have their default mail client setup, some do, some do but prefer an alternative, etc. better experience is to tell the user to open up their email and click the link instead of trying to open it for them.

**Comment by annastoilova** [comment]
> waiting on design from @annastoilova. does not look realistic to fix in code. there is too much user/phone variation, some people don't have their default mail client setup, some do, some do but prefer an alternative, etc. better experience is to tell the user to open up their email and click the link instead of trying to open it for them.

Agreed, that's what I was gonna say. Will include in the design.

**Comment by annastoilova** [comment]
Remove button - As per same design on other issues in this milestone

![Inbox](https://user-images.githubusercontent.com/19438822/113950601-a8db3d00-9809-11eb-8af1-8118e792ba66.png)
