### ISSUE TITLE
Add TIKI information section

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#142]
As I user, I want to be able to see TIKI information in a relevant space (not mixed with my account settings), so that I am informed with what's happening at TIKI.

**Rees** in _Design Feedback Discord channel_: 
"When I clicked the account icon in the upper left corner, its kinda tedious to scroll all the way down to see irrelevant information. It's kinda confusing to see the news and whatnot in it. I think its better if the other info (see picture 3) have their own menu bar or at least not in the account section. 

**Hakor** in _Figma Comments_
"Latest news, TIKI tribe and Follow us shouldn't be here, it's not part of the account..."

![image](https://user-images.githubusercontent.com/19438822/123702133-ab728f00-d85a-11eb-8c1b-096617734d18.png)

**This includes:**
1. TIKI's Coming Next feature
2. Latest news from TIKI
3. TIKI communities links
4. TIKI social media links

Anna to design where this section should go!

![image](https://user-images.githubusercontent.com/19438822/123699704-7c0e5300-d857-11eb-8d5e-bfe9081b37c8.png)

![image](https://user-images.githubusercontent.com/19438822/123699738-82043400-d857-11eb-9003-dda7479419bf.png)

**Comment by annastoilova** [comment]
Keep this section as it is now (like in prototype)

**Comment by mike-audi** [comment]
close for #316
