### ISSUE TITLE
Sharing functionality for all email cards

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#148]
As a user, I want to be able to share information on the card that I find interesting, so that I gather some interest from my social and personal networks.

Acceptance criteria: I can now share each card's content that is showing my data and information on my email usage.

Add share button and screenshot the content on the screen for sharing.
![image](https://user-images.githubusercontent.com/19438822/123715466-42961180-d870-11eb-8ea4-8cd8a16c0fb7.png)

**Comment by mike-audi** [comment]
close. not needed currently
