### ISSUE TITLE
Summary of email activity

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#150]
As a user, I want to see a summary of my email activity, so I have a clear view who's emailing me the most and what my email habits are.

Acceptance criteria: As a user who's linked their Gmail account, I can see at a glance valuable information about my email activity:
- Headline: "_In the past 1 week, you got more than 200 emails that you didn’t open_"
   technical considerations: Notify user if they have more than 50 emails that they haven't opened. Round it to the closest  00 ie. "more than 100 emails" "more than 1200 emails". If they have less than 50 unopened emails for that week, tey "In the past month..."
   
  - Body: "_Adweek, +55 others email you  more than once a week_" 
  technical considerations: present the logos of the top 3 companies that email them, and list how many email them more than once a week
  
![image](https://user-images.githubusercontent.com/19438822/123818356-d4ddfa00-d8f0-11eb-8bfe-8d620ebca546.png)

**Comment by ricardobrg** [comment]
Needs definition of which data will be displayed and the origin of this data.

**Comment by mike-audi** [comment]
closing. feature not needed
