### ISSUE TITLE
Emailing companies title & logo

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#151]
As a user, I want to see who's emailing me so that I can understand my email activity better.

Acceptance criteria: User can see who is emailing them by reading the headline and seeing the company's recognizable logo.

Technical specs: Include the name of the company as a title and include their logo (pull the company's logo from a public database)

![image](https://user-images.githubusercontent.com/19438822/123819083-69485c80-d8f1-11eb-8484-0f300ee2dec3.png)

![image](https://user-images.githubusercontent.com/19438822/123819207-81b87700-d8f1-11eb-80e7-440708c9158c.png)

![image](https://user-images.githubusercontent.com/19438822/123819244-89781b80-d8f1-11eb-83e2-8f27c2d41b26.png)

![image](https://user-images.githubusercontent.com/19438822/123819290-9268ed00-d8f1-11eb-82c9-82f1014a836b.png)

**Comment by annastoilova** [comment]
In the case where there's no logo or company name available -> see Figma

![image](https://user-images.githubusercontent.com/19438822/126236450-a6c86f33-b1ec-4a1b-9ece-d566f692d0e4.png)

**Comment by mike-audi** [comment]
The backend API is complete. Assigning to @ricardobrg to complete the UI.
