### ISSUE TITLE
Security score (for each email list) 

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#157]
As a user, I want to know how secure an email list (ie. a company holding my email address is), so that I can make an informed decision whether to unsubscribe from their emails, or keep them going.

Acceptance criteria: I can see a security/safety score for each email list I have.

Technical Specs: TBC

![image](https://user-images.githubusercontent.com/19438822/123838390-dd8bfb80-d903-11eb-9ac9-66d72cbaab33.png)

![image](https://user-images.githubusercontent.com/19438822/123838415-e41a7300-d903-11eb-8975-4266d0915f6e.png)

![image](https://user-images.githubusercontent.com/19438822/123838446-ebda1780-d903-11eb-82e8-a7af615f39f9.png)

**Comment by annastoilova** [comment]
Needs definitions

**Comment by mike-audi** [comment]
@annastoilova The security score will use a combination of two factors

1. A rating based on the sensitivity of the business emailing you, for example medical or financial information vs a clothing company

2. A rating based on known recent security breaches/hacks

**Comment by annastoilova** [comment]
@mike-audi can we point the sources we'll be using, i.e. _https://haveibeenpwned.com/_. Let me know

**Comment by annastoilova** [comment]
Here is the UI for the Security Score pop up @mike-audi 

![image](https://user-images.githubusercontent.com/19438822/125869890-02333605-c975-4217-b4f7-449856f851bc.png)

**Comment by annastoilova** [comment]
In the case of no security score available just yet:
![image](https://user-images.githubusercontent.com/19438822/126236872-021b8a4f-a678-4a62-9ab9-f7a1aea89b76.png)

**Comment by annastoilova** [comment]
Alternative design: 

![image](https://user-images.githubusercontent.com/19438822/126238680-62a16f22-5b40-4cf9-8531-f19baca554ee.png)

Design where there's no score available:

![image](https://user-images.githubusercontent.com/19438822/126238704-a518c3a6-c950-4897-8e46-7ae42059d757.png)

**Comment by mike-audi** [comment]
The two APIs we use are http://bigpicture.io/ (Company Information) and http://haveibeenpwned.com/ (Breach data).

@ricardobrg scores are provided between 0 & 1 with 1 being the most breached or most sensitive. To calculate a star rating from 0 - 5 just subtract the security score from 1 and then multiply by 5. 

The backend API is complete and rolled out. The corresponding app API code has been added to a branch off of develop.

**Comment by annastoilova** [comment]
@mike-audi Can we have the score so that 10 / 10 is the best?
Also, color coding as per your idea can be:

1, 2 and 3 - red
4, 5 and 6 - yellow
7, 8 and 9 - green

![image](https://user-images.githubusercontent.com/19438822/128762365-e4247f98-7770-4849-b6b1-97ffbea8d7b2.png)
