### ISSUE TITLE
Design new onboarding screens

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#166]
As a user, I want to be shown what to do when I first use the TIKI app, so I can get to know and use the app easily.

Design an onboarding experience that helps guide the user, as per the new functionalities of the app (release 0.2.0), 

Goal of the onboarding: To help the user fulfull their tasks when they first get to use the app.

**Comment by ricardobrg** [comment]
needs the definition of the onboarding process

**Comment by mike-audi** [comment]
close. will create relevant stories once designed.
