### ISSUE TITLE
Data screen - finish design of data score

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#172]
As a developer, I want the design finalised, so I can build it. :)

As a user, I want to have a simple and clear way to see how my account scores in terms of data privacy and security, so that I know what to do / how to fix it. 

Acceptance criteria: A finished design for development to work from.

Technical specs: To finish the design of:

- Design score section:
![image](https://user-images.githubusercontent.com/19438822/124288631-53cd6f80-db49-11eb-87fb-b8f350dc914e.png)

- Illustrations: - may be add our pineapple in various states - sad, neutral, happy
![image](https://user-images.githubusercontent.com/19438822/124289376-26cd8c80-db4a-11eb-8e46-a9ad77e0179e.png)

- Improve score button

- Improve score section: explaining how people can improve their score.

**Comment by mike-audi** [comment]
close. will create relevant stories once feature is designed.
