### ISSUE TITLE
Data: See your Gmail past choices

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#173]
As a user, I want to know what data choices I have made in the past, so I can be informed and change them, if needed. 

Acceptance criteria: I can see a list of the choices I have made, and change them if I want to.

[To finalise design]

![image](https://user-images.githubusercontent.com/19438822/124301506-d9581c00-db57-11eb-9c77-28515a33c14e.png)

**Comment by ricardobrg** [comment]
To be discussed - how do we want to implement that log in the database?

**Comment by mike-audi** [comment]
close. not needed for now. will reopen once designed.
