### ISSUE TITLE
It's not obvious where the backup keys were downloaded

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#18]
When you click backup, a screen shot of the QR code is backed up locally however its not explained to the user where this is saved. Additionally, this file should be "prettied up" with a title, and a textual representation of the keys just incase the QR code fails.

**Comment by annastoilova** [comment]
> When you click backup, a screen shot of the QR code is backed up locally however its not explained to the user where this is saved. Additionally, this file should be "prettied up" with a title, and a textual representation of the keys just incase the QR code fails.

Agreed, we could solve this by an explanation on the Keys page, something like "your keys have now been save in your phone's files or photos folder."

I will add to the design of the Keys page.

**Comment by mike-audi** [comment]
Another option if you don't want to put it on the screen itself, we could a local push notification so it shows up in Notification Center and if they click on it, it will open the file (just like how downloads work)

**Comment by annastoilova** [comment]
Will work on this tomorrow

**Comment by annastoilova** [comment]
Definitely let's include Push notification.
For those that have the push notifications off, let's have it on the screen, too. 
How about something like this (like an informational modal)?

![Screenshot 2021-04-09 at 02 11 30](https://user-images.githubusercontent.com/19438822/114114604-173b0080-98d9-11eb-8a06-d70230d98d65.png)

**Comment by mike-audi** [comment]
Would it not be best if they could click something and it would open the file? It's probably going to hard for some to even find it in their files.

**Comment by annastoilova** [comment]
Definitely sounds good to do that, as well. My thinking is, that they'll then. close the file, and STILL not know where the file has been saved? This is what I'd do anyway....
So, let's have both options?

**Comment by annastoilova** [comment]
This flow could work
![Screenshot 2021-04-09 at 20 00 08](https://user-images.githubusercontent.com/19438822/114228548-7dbe2e00-996e-11eb-8961-bc7fa6f004b7.png)

**Comment by mike-audi** [comment]
Add as part of this feature: 
As a user, I am not sure if TIKI has saved the keys on my phone (no confirmation, or anything)

**Comment by mike-audi** [comment]
Review iOS & Android permissions to see if additional permissions are needed to download the file.

**Comment by mike-audi** [comment]
Per discussion with Anna. 

We want to offer users multiple options in how to backup their keys. 
- integration with 1pass/lastpass/other.
- print
- copy
- download
