### ISSUE TITLE
Standardize widget sizing

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#184]
Setup a config class for common numbers like margins & paddings

**Comment by mike-audi** [comment]
the math still doesn't work, sizer sps do not align, they're too large. need to figure out the right scaling equation. 

notes to self:
 1. sp = dp but also scales when the user changes their app’s font size. 
 2. px = dp * (dpi / 160)
3. dp = px / 1.0179375 (when designed for iphone x/11)
4. formula still doesnt seem right. 9.1 sp ~ 11px

**Comment by ricardobrg** [comment]
closing in favor of #309
