### ISSUE TITLE
Cache the TIKI tribe count

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#19]
Cache the TIKI tribe count so when the app reloads it is the last known amount not the random placeholder amount it briefly shows right now.

![image](https://user-images.githubusercontent.com/3769672/113090102-02fb5300-91b7-11eb-8409-0d8d79da9653.png)

**Comment by ricardobrg** [comment]
nevermind, found it

**Comment by ricardobrg** [comment]
This cache will be done in SQLite. We need an app_config table to store key-value pairs that are not privacy sensitive.

**Comment by mike-audi** [comment]
Also cache the # of referred people

![image](https://user-images.githubusercontent.com/3769672/118751305-16c64b80-b82f-11eb-9be4-698aec366041.png)

**Comment by ricardobrg** [comment]
#175
