### ISSUE TITLE
Add support knowledge base

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#198]
As a user, I want to be able to easily find answers to my questions, and contact a member of TIKI's support team, if neccesary.

Теchnical specs:  Use existing APIs (when available) to build this section. 

In this order of priority, build:
1. FAQ ready answers (can be hosted on a website, which opens in-app)
2. Chat (sunshine conversations)
3. Search functionality (as most time consuming)

For designs, see #162

**Comment by annastoilova** [comment]
UI designs created - see in Figma / Product / Beta App under a new page "support section"

![image](https://user-images.githubusercontent.com/19438822/125952085-582c1707-2208-494b-a573-020e8e1e33b8.png)

![image](https://user-images.githubusercontent.com/19438822/125952135-27355d3d-c164-4256-921e-72e442d9dd64.png)

![image](https://user-images.githubusercontent.com/19438822/125952194-b69b242d-0d40-4c69-abf8-d7f95319d29c.png)

![image](https://user-images.githubusercontent.com/19438822/125952240-9de42c9b-f66b-4e7c-adb2-85906b7fe2b6.png)

**Comment by ricardobrg** [comment]
TBD after #322 
Talk to Shane about the UI

**Comment by ricardobrg** [comment]
1. done
2. UI ready updating sdk
3. tbd

**Comment by ricardobrg** [comment]
following it up in #325 #346 and #347
