### ISSUE TITLE
Define dev/qa/release pipelines

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#206]
We should have at least 2 pipelines, and maybe 3.
- dev pipeline: which will run in every develop branch merge, like the one in 0.2.0.
- release pipeline: which will run in every tag creation and will create a release, like the old one.
- qa pipeline: which will run in every main branch merge to assure that all tests pass.

Since we don't have the tests yet, we should create the dev/release pipelines. 
#39

**Comment by mike-audi** [comment]
closing this story. will revisit once we have automated testing and create dedicated stories per pipeline
