### ISSUE TITLE
Add Report a bug button in Account Settings

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#213]
As a Product / technical Owner I want to be informed of bugs in the tiki app
As a user, I want to easily inform the TIKI team of any bugs I encounter, without having to spend a lot of time.

Add a "report a bug" button to Account Settings to easily allow users to report a bug

![image](https://user-images.githubusercontent.com/19438822/125954561-c08474db-27f9-4bf5-a6c6-a32bc5b4bc3e.png)

**Comment by ricardobrg** [comment]
Where should this button take to? Maybe an easy fix?

**Comment by mike-audi** [comment]
Need to get Shane involved in this discussion to determine what we want the bug report to be.

**Comment by ricardobrg** [comment]
closing in favor of https://github.com/tiki/upvoty
