### ISSUE TITLE
User does not get email on multiple email accounts

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#217]
"Ive already checked spam and just rechecked now nothing there.. ive try with gmail, hotmail and a work email @rona.ca and none of them where able to received the registration email."

Shane: Any insight on a user who is not getting a registration email sent to them (multiple email tries & not in spam) sendgrid? bug? us? them?

wolfien@gmail.com is the email he used to contact
User based in canada i think

**Comment by ricardobrg** [comment]
Was it addressed?

**Comment by mike-audi** [comment]
unable to reproduce. only happens for the one user. closing for now.
