### ISSUE TITLE
Update app images to latest

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#22]
<img width="375" alt="Securing account 5" src="https://user-images.githubusercontent.com/3769672/113090641-3ee2e800-91b8-11eb-89c6-d7c44fa3ea6f.png">

![Email](https://user-images.githubusercontent.com/3769672/113090704-5f12a700-91b8-11eb-9536-8c67fdff23d3.png)

**Comment by annastoilova** [comment]
These will eventually be animations, but for now, I will provide the latest .svgs in Figma.

**Comment by annastoilova** [comment]
Illustrations updated in Figma, and attached here, too.

![Pineapple-Illustration-_-01_correct_colours](https://user-images.githubusercontent.com/19438822/113461708-8b772f00-9415-11eb-9263-2b722b766f70.png)
![Pineapple-Illustration-_-02_correct_colours](https://user-images.githubusercontent.com/19438822/113461709-8ca85c00-9415-11eb-883f-d96853b80e10.png)
![Pineapple-Illustration-_-03_correct_colours](https://user-images.githubusercontent.com/19438822/113461710-8dd98900-9415-11eb-9ac7-0749e87e7900.png)
