### ISSUE TITLE
Alert users when there is a new app update

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#226]
for reference, here's an example of how to do it in android:

![](https://cdn.shortpixel.ai/client/q_glossy,ret_img,w_825/https://androiddvlpr.com/wp-content/uploads/2019/07/flexible-app-update.png)

https://androiddvlpr.com/android-app-update-notification/

**Comment by ricardobrg** [comment]
https://pub.dev/packages/upgrader

Just adding here for future discussion

**Comment by mike-audi** [comment]
Does (https://pub.dev/packages/upgrader) work for TestFlight & Android Beta?

**Comment by ricardobrg** [comment]
check
#539 
#547 
#546 
#545
