### ISSUE TITLE
TBC - Choices Cards - add 3rd swiping option

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#227]
Raised by Watrex on 18th July:

"i mean what if by swiping the card down you have ignore for now option
and the cards even go when im just taping on them"

![image](https://user-images.githubusercontent.com/19438822/126080973-58f9c6b3-ba70-490b-a838-967b78c3ce31.png)

![image](https://user-images.githubusercontent.com/19438822/126080977-ce77b90c-b360-4515-8b62-f440a0394aa5.png)

**Comment by annastoilova** [comment]
"Ignore now" - sliding down.
reminder in ? hours ? days

For example, in antivirus you can ignore some virus, or choose to quarantine them.

**Comment by ricardobrg** [comment]
For now the "keep them" option ignores it. Maybe in the future, it could be checked for different scenarios, but not for email.
