### ISSUE TITLE
Message in choices when loading data

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#229]
Add message to say 

"We're working on getting your data in this space. Hold on for a few seconds

**Comment by annastoilova** [comment]
Something like this @ricardobrg 

![image](https://user-images.githubusercontent.com/19438822/126479838-e32313ec-ac18-4af1-93d3-6b888babe592.png)

**Comment by mike-audi** [comment]
fix the bug, it should show up as the null state as until the email account is finished (you can tell by the gmail last fetch date in the app data)
