### ISSUE TITLE
Add information cards to Home Screen

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#24]
<img width="375" alt="Home" src="https://user-images.githubusercontent.com/3769672/113091159-5c648180-91b9-11eb-9f31-db2332397274.png">

**Comment by annastoilova** [comment]
Added a card for next release

<img width="375" alt="Home 1" src="https://user-images.githubusercontent.com/19438822/113952865-76800e80-980e-11eb-8f52-f81ac061dd16.png">

**Comment by annastoilova** [comment]
[0.0.8.zip](https://github.com/tiki/app/files/6474992/0.0.8.zip)

@ricardobrg Folder with illustrative assets attached -> It contains both .svg and .png

**Comment by ricardobrg** [comment]
To finish in 0.0.9
