### ISSUE TITLE
Cards - fetching data: allow user to refresh 

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#247]
As a user, I want to be able to see information that my data is still being fetched so that I know there are more cards are coming. If the app is stuck at fetching data, and doesn't deliver more cards quickly, it would be helpful if I could do something.

Technical requirements - why this is needed:
Supplied by @mike-audi
 

Currently we are displaying а message and nothing else.

![image](https://user-images.githubusercontent.com/19438822/129448363-c6ecaa1d-f864-455f-bb4b-cf340082655f.png)

**Comment by mike-audi** [comment]
Technical Requirements:
1. Expose the status of syncs per linked account (last sync'd date, timeout, error, etc.). The last sync'd date is already stored in the app data under key `ApiAppDataKey.gmailLastFetch`. 

2. Add a force'd retry via a user action, for example in mail clients, when the user pulls down to refresh it instantly triggers a fetch of any new emails. This should for a new sync event, not re-index their entire account from scratch. This logic is already implemented in `checkGmail` in `data_bkg_service.dart`. Simply connect the user action even to `checkGmail(force: true);`

**Comment by mike-audi** [comment]
In addition to the last sync date we can optionally also expose 

- the number of emails sync'd 
- if the sync is stuck
- if the sync failed
- if the sync succeeded

**Comment by annastoilova** [comment]
Working on this, but let's also discuss at stand up.

**Comment by annastoilova** [comment]
This journey has been designed as in Figma: 

![image](https://user-images.githubusercontent.com/19438822/130298783-6efe070f-50b9-45e2-85cc-5baa44212b39.png)

Separate tickets will be created for building this, marked as done from design perspective.
