### ISSUE TITLE
*Urgent* bug - users can't link Gmail account

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#249]
Multiple users have reported that they can't add their Gmail account.

When adding account, their app gets stuck on loading: 

https://user-images.githubusercontent.com/19438822/129448813-e7893cf8-9806-4796-9931-c754017d4fae.mp4

**Comment by mike-audi** [comment]
To fix this issue we need official OAuth approval from Google. There are two outstanding items:

1. I need to provide them with a video showing and explaining exactly how the unsubscribe email send function works

2. We need to change the add gmail account to sign in with google per these guidelines: https://developers.google.com/identity/branding-guidelines#top_of_page

@ricardobrg can you please build the button immediately. I will need it before recording the video

**Comment by annastoilova** [comment]
Blocker: Google Policies
Next steps: talking to lawyer about changing our policy.
