### ISSUE TITLE
Add terms of service & privacy policy to login screen

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#25]
Write TOS and update Privacy Policy first.

<img width="375" alt="Sign up 3" src="https://user-images.githubusercontent.com/3769672/113091223-7bfbaa00-91b9-11eb-93f1-3b422f2b039c.png">

**Comment by mike-audi** [comment]
[TIKI Mobile App Terms and Conditions.DOCX](https://github.com/tiki/app/files/6455550/TIKI.Mobile.App.Terms.and.Conditions.DOCX)
[TIKI Privacy Notice (6apr2021).DOCX](https://github.com/tiki/app/files/6455551/TIKI.Privacy.Notice.6apr2021.DOCX)

**Comment by mike-audi** [comment]
the highlighted section missing in Terms & Conditions is 6 fyi

**Comment by mike-audi** [comment]
see branch feature/#25 for files 

https://github.com/tiki/app/tree/feature/%2325

**Comment by ricardobrg** [comment]
WIP to finish in 0.0.9
