### ISSUE TITLE
As a user I want a helpful error page

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#252]
technical specifications & user story to be provided by @mike-audi

**Comment by mike-audi** [comment]
As a user I don't want a helpful error page when/if the app experiences a "hard crash" or "silent failure".  

Use the [ErrorWidgetBuilder](https://api.flutter.dev/flutter/widgets/ErrorWidget/builder.html) as part of the `MaterialApp` widget to provide the page as its own slice. 

1. The page should be tightly coupled with Sentry providing stacktrace and other helpful ANONYMOUS debugging 
parameters. 
2. The page can have different text/states depending on the type of error, like no internet vs random crash
3. It would be helpful if the user could add stuff like a screenshot or text when it happens
4. The page could include some sort of support/faq integration

**Comment by ricardobrg** [comment]
include in #355

**Comment by ricardobrg** [comment]
This should be implemented in 
https://github.com/tiki/app/blob/bfa52ee2e592ccf426eb4816ef2024a2549f4250/lib/main.dart#L23-L27

Refer to https://api.flutter.dev/flutter/foundation/FlutterError/onError.html
