### ISSUE TITLE
Clean up images

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#253]
The app is starting to balloon in size (25MB). Complete this ticket after #180 

1. Remove all unused images
2. Add missing image sizes (0.5x, 0.75x, 1x, 1.5x, 2x, 3x, 4x)

**Comment by ricardobrg** [comment]
#309 will move lots of images to icons, reducing overhead.

This should be done after that.

**Comment by ricardobrg** [comment]
#451 will handle this
