### ISSUE TITLE
Research other email integrations

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#264]
Research Policies of **major email hosts** so that we know whether we can do (successfully execute) an integration with them before we even touch the code.

Start with:
**1. Outlook
2. Apple Mail Host**

If Outlook works, let's go with this, as we know that most our users are Android, so unlikely that they use Apple mail.
Unfortunately, due to the fact that most users are Android users Apple Iphone email client will not be the most popular option.

### Email client usage worldwide, collected from 1.1 billion email opens - July 2021

For all users: 
https://emailclientmarketshare.com/
#2 is Gmail with 34% 
#3 is Apple Mail with 9%
#4 is Outlook with 6%
#5 Yahoo!Mail - 4%

2019 stats:
https://www.statista.com/chart/17570/most-popular-email-clients/

"**Gmail has a market share of 25%.**
Gmail and Apple iPhone are the two most favored solutions for reading emails. Together, they account for 62% of the email client market share. Data from December 2019 shows that iPhone accounts for 37% of all email opens, followed by Gmail with 25%.

Apple Mail is the next most commonly used email solution, with 10% of all opens, followed by Outlook and Yahoo! Mail with 8% and 6%, respectively, to round out the top 5.

(Email Client Market Share)"

![image](https://user-images.githubusercontent.com/19438822/130263674-22928a2d-27e8-4642-9263-10a34baaa226.png)

**Comment by mike-audi** [comment]
Okay, we should be able to do a Microsoft integration using their new Graph API. Microsoft's identity platform TOS are linked below, but there does not seem to be any additional approval required other than registering the application. 

https://docs.microsoft.com/en-us/graph/auth/auth-concepts
https://docs.microsoft.com/en-us/outlook/rest/get-started
https://docs.microsoft.com/en-us/legal/microsoft-identity-platform/terms-of-use
