### ISSUE TITLE
Implement Generic OAuth client

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#265]
Implement a standard OAuth client which can

1. Issue a token for any compliant service
2. Securely store tokens locally for reuse on behalf of the user
3. Refresh expired tokens

**Comment by ricardobrg** [comment]
First draft design - for reference

ApiAuthService

add account
	- oauth interactive login
		id
		provider
		account (same as email table)
		save access token 
		save access token expiration
		save refresh token
		save refresh token expiration
		
	- appapi save which accounts need to relogin

request
get access token from db
	- expired
		- refresh token expired
			send user to oauth interactive login again
		- refresh token not expired
			make request to update access token
			- refresh fails
				send user to oauth interactive login again		
			- refresh succeeds
				make request
				
	- not expired
	make request
 	- update refresh token if needed

remove account
	- revoke token
	- remove the record access token
		remove refresh token
	
Google OAuth flow - https://developers.google.com/identity/protocols/oauth2/native-app#offline
Microsoft OAuth flow - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
