### ISSUE TITLE
Add error state to cards fetching screen

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#269]
As Technical PM, I need to know why users are getting a bug where stop seeing cards. 

Acceptance criteria: Screen shows reason for Error.

Error states to be defined by @mike-audi 
Follow UX flow in Figma for further instructions on where the error state appears.

![image](https://user-images.githubusercontent.com/19438822/130481226-7c2dc403-cfdf-4f18-abf3-9ab48ae3f806.png)

![image](https://user-images.githubusercontent.com/19438822/130481450-c0033052-07ef-448e-8a1b-195db7d6e45e.png)

**Comment by mike-audi** [comment]
close. this will be addressed in #310
