### ISSUE TITLE
Add retry functionality to cards fetching screen 

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#270]
As a user, I want to be able to know if the app is stuck fetching cards and be able to do something. 

Acceptance criteria: Change user interface as per design below and add a Retry button for user to keep trying to fetch data. 

Add "Last synced" info for further information, if the problem is reported to us for support.

![image](https://user-images.githubusercontent.com/19438822/130481695-9349ff00-11ae-4fca-8304-0b4d05265546.png)

See #269 for Error state functionality.

**Comment by ricardobrg** [comment]
#287 needs to implement this state

**Comment by mike-audi** [comment]
close. open new issue related to #310
