### ISSUE TITLE
IPad/Tablet Scaling

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#28]
All screens just scale as is. Looks awkward & giant. Should make a dedicated tablet UI.

![Simulator Screen Shot - iPad (8th generation) - 2021-03-31 at 00 47 10](https://user-images.githubusercontent.com/3769672/113091777-a69a3280-91ba-11eb-844e-8664627285cb.png)

**Comment by mike-audi** [comment]
Officially a bug, In addition to not scaling gracefully. Purposefully non-scrollable screens like the home page do not work since they're scaled off the page.

![unknown1](https://user-images.githubusercontent.com/3769672/115066686-e1d87900-9ebd-11eb-92f0-3989980229b8.png)
![unknown](https://user-images.githubusercontent.com/3769672/115066706-e43ad300-9ebd-11eb-99ca-66438bad0b67.png)

**Comment by ricardobrg** [comment]
WIll be treated in #58
