### ISSUE TITLE
Missing log out button

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#3]
Users should be able to logout of the TIKI app. When a user logs out, by default, it should delete all locally stored TIKI data except for their security keys. Users should have the additional option to delete their security keys (if they so wish) from local storage.

![X - 1](https://user-images.githubusercontent.com/3769672/113079825-c8d48600-91a3-11eb-866f-c79ed56a4510.png)

**Comment by mike-audi** [comment]
waiting on design from @annastoilova. moving to later milestone

**Comment by annastoilova** [comment]
For simplicity and usability, position at the bottom of the page, with or without scrolling.
<img width="375" alt="Home" src="https://user-images.githubusercontent.com/19438822/113950732-f0fa5f80-9809-11eb-952e-5ef0d7408e2c.png">
<img width="375" alt="3" src="https://user-images.githubusercontent.com/19438822/113950736-f48de680-9809-11eb-9627-7b49a08c6d79.png">
