### ISSUE TITLE
Key generation with backup flow

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#331]
When generating keys the following flow should be implemented.

1. Generate keys
2. User enters 6 digit pin code
3. User enters 8 digit+ passphrase (include strength meter & possibly a HIBP check)
4. AES256 encrypt keys + address using passphrase
5. Post to TIKI's backup service the hashed email, hashed pin code, and encrypted keys

**Comment by ricardobrg** [comment]
implemented in https://github.com/tiki/login
