### ISSUE TITLE
Securing keys screen - add animation  

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#36]
Replace the illustration to be the animation done in Lottie, to test how it works before doing the other animations!

![Securing_account_animation](https://user-images.githubusercontent.com/19438822/113950949-75e57900-980a-11eb-89a2-56ca8bbf4eb2.gif)

**Comment by annastoilova** [comment]
Thanks Mike, I also forwarded the email with the JSON files
Blob = the white background behind the character.

**Comment by ricardobrg** [comment]
resolved by #70 . We have animations, yay!
