### ISSUE TITLE
Login flow integration and manual tests

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#368]

**Comment by mike-audi** [comment]
Error States

On Backup:
- ~invalid pin code~
- ~invalid passphrase~
- fails on server side: error with a retry button
- no internet: error with a retry button

On Recovery:
- invalid pin code: you won't even get keys back, user goes back to the pin code screen saying invalid
- invalid passphrase: you won't be able to decrypt the keys, user goes back to the passphrase screen
- too many recovery attempts: if the user tries to recover keys more than 5 times, the server will throw an error, send user to error screen with a contact support & their unique recovery code. 
- fails on server side: error with a retry button
- no internet: error with a retry button

On Cycle:
- ~invalid pin code~
- ~invalid passphrase~
- duplicate pin code: force the user to enter a different pin code
- duplicate passphrase: force the user to enter a different pin code
- fails on server side: error with a retry button
- no internet: error with a retry button

**Comment by ricardobrg** [comment]
in progress
- keys creation UI - style and clean.
- automated tests for the errors in the keys creation flow.

TODO
- automated testing for qr code recovery with error handling 
- keys pincode/passphrase recovery automated tests with error handling

**Comment by mike-audi** [comment]
automated tests are still wonky. will manual test and record results here for subsequent stories.

- [x] backup

 
new issue: after submitting a valid passphrase the UI should move right to the creating keys animation

**Comment by mike-audi** [comment]
- QR code recover: failed

app does not even present the necessary UI

**Comment by mike-audi** [comment]
- remote recover: pass

new issue: add a success ui screen before cycling the pin/pass

**Comment by mike-audi** [comment]
– cycle require new passphrase: pass

new issue: update the text from "Please use a different passphrase" to something more helpful

**Comment by mike-audi** [comment]
- cycle require new pin code: failed

bug: UI should stop the user from proceeding without a new pin code same as passphrase

**Comment by mike-audi** [comment]
- bad passphrase on recover: fail

bug: UI should alert the user to a bad passphrase.

**Comment by mike-audi** [comment]
- keys cycle: pass

**Comment by mike-audi** [comment]
new issue: add a network request animation or something like that for after submitting the backup passphrase & cycle passphrase.

**Comment by mike-audi** [comment]
- too many recovery attempts: failed

does not show error just, just stays stuck on the passphrase screen

**Comment by mike-audi** [comment]
- invalid pin: failed

stays stuck on the passphrase screen

new issue: wallet should return more explicit errors. currently it returns a null error for bad pin, block cipher error for bad passphrase, and the actual http response for a locked account.

**Comment by mike-audi** [comment]
- no internet: failed

stays stuck on the passphrase screen

**Comment by mike-audi** [comment]
closing in favor of new, specific issues
