### ISSUE TITLE
Sentry Release

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#39]
Move sentry CI/CD release to a separate job. It will not run on Mac container only Linux container

**Comment by ricardobrg** [comment]
@mike-audi What is the progress on this? Should I do anything?

**Comment by ricardobrg** [comment]
It is still falling. Moved to 0.1.1 in order to focus on the deliverables of 0.1.0

**Comment by ricardobrg** [comment]
I will leave this closed but we should discuss a different pipeline for release that will run like the old one.
- the dev pipeline in every develop branch merge
- the release pipeline in every tag creation
