### ISSUE TITLE
Integrate Microsoft Provider Message Fetch Function into App

### ISSUE THREAD

**Issue by sfaria27** [tiki/app#394]
After fetching a users inbox, fetch all messages

Acceptance criteria:
1. Messages should be saved to local db

**Comment by ricardobrg** [comment]
![simulator_screenshot_5C8E3717-1488-4041-8F51-3C91DA7D751C](https://user-images.githubusercontent.com/8357343/155358292-bb044534-b736-4084-9b27-dc8c5b2ee373.png)


![simulator_screenshot_E7743496-EDBA-41CE-9B64-320A995A5DB9](https://user-images.githubusercontent.com/8357343/155358393-4ff3a36c-4337-4b6b-9eb3-a8f85e2aea3c.png)
