### ISSUE TITLE
Integrate google provider login flow into app

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#397]
Integrate Google Provider login flow into app, replacing google api.

Acceptance criteria
1. The user is able to login into Google account through the account widget.

**Comment by sfaria27** [comment]
@ricardobrg to post screenshot

**Comment by ricardobrg** [comment]
![simulator_screenshot_47243ED3-4FA7-42E6-B73A-DAE0D60B80BE](https://user-images.githubusercontent.com/8357343/155203372-8cc989fa-83fe-47f2-bdb4-502f55323685.png)
![simulator_screenshot_4816D5E0-1FF0-43DA-82BC-4894F7E11715](https://user-images.githubusercontent.com/8357343/155203452-feed716d-d562-443c-8654-03f4fce2e02a.png)
