### ISSUE TITLE
Save google provider account data into local database

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#398]
After the user is logged in, the account data should be saved into the database.

Acceptance criteria:

1. The account data is saved into the database to recreate the account widget with logged-in data.

**Comment by sfaria27** [comment]
@ricardobrg to add screen record

**Comment by ricardobrg** [comment]
https://user-images.githubusercontent.com/8357343/155414940-c4ce1fd1-026b-4b29-8458-27321242258e.mov
