### ISSUE TITLE
Review and refactor slice architecture

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#474]
Review the code structure and refactor it to slice architecture.

Acceptance criteria
1 - App running with updated code.

**Comment by ricardobrg** [comment]
blocked by https://github.com/tiki/user_account/issues/35

**Comment by ricardobrg** [comment]
Some of this is done in https://github.com/tiki/app/tree/Review_and_refactor_slice_architecture%23474

**Comment by mike-audi** [comment]
<img width="765" alt="Screen Shot 2022-05-06 at 10 29 39 PM" src="https://user-images.githubusercontent.com/3769672/167236390-aa809fa9-0388-40ca-bcfb-247c95cff97b.png">
