### ISSUE TITLE
Use different Database for different users

### ISSUE THREAD

**Issue by ricardobrg** [tiki/app#476]
As a developer I need to ensure that each account database file has a unique name.

When the user changes the logged in TIKI account, the app tries to open the database with the new account private key, but it cannot be unencrypted because the key is different.

Acceptance criteria:
1 - Each account has its own unique database file.
2 - When login/logout the correct database is loaded with the specific cards and state.

**Comment by mike-audi** [comment]
@ricardobrg to encode the address as hex to ensure safe filename chars

**Comment by ricardobrg** [comment]
![Simulator Screen Recording - iPhone 8 - 2022-05-16 at 17 56 22](https://user-images.githubusercontent.com/8357343/168681543-ed17af8d-2bb2-43c6-9f29-f19d7119bf9e.gif)

**Comment by ricardobrg** [comment]
hex encoded filenames
<img width="594" alt="Captura de Tela 2022-05-16 às 17 58 21" src="https://user-images.githubusercontent.com/8357343/168681716-6bd4012b-e869-4307-af07-ff161fa90924.png">
