### ISSUE TITLE
Configure sentry monitoring

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#479]
Configure sentry monitoring for error & bug management throughout our full stack. 

Acceptance Criteria:
1. ~Flag data pipeline issues~ 
https://github.com/tiki/data/issues/68
https://github.com/tiki/localgraph/issues/8
2. ~Flag blockchain issues~
https://github.com/tiki/wallet/issues/32
https://github.com/tiki/localchain/issues/18
3. ~Flag UI issues~
https://github.com/tiki/app/issues/491

**Comment by ricardobrg** [comment]
TBD after #355
