### ISSUE TITLE
Configure Amplitude

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#480]
As a developer, I should be able to monitor KPIs anonymously from Amplitude.

Add/update Amplite charts and spaces for
App Usage

- MAUs
- Num of new wallets created
- Num of returning users
  - QR code
  - pin/passphrass
- Num of linked accounts (gmail/outlook)
- Num of decisions

Data 
- Num of indexed emails
- Num of fetched emails
- Num of data signals

Blockchain
- Num of NFTs minted
- Num of backed up NFTs

Acceptance Criteria:
1 - Test scenario: send a test event and get it in the Amplitude Dashboard.
2 - Amplitude dashboard configured with spaces and charts

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/174679789-241ae741-6584-4885-ae16-5597a4b4cad0.png)

**Comment by ricardobrg** [comment]
Amplitude dashboard configuration tbd in #497
