### ISSUE TITLE
Add Amplitude

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#49]
Amplitude was removed during the re-write. Re-add as a repo.

**Comment by mike-audi** [comment]
@mike-audi to setup @ricardobrg with amplitude

**Comment by mike-audi** [comment]
@ricardobrg when you go to implement this, make sure during initialization to add

```
await amplitude.enableCoppaControl(); //disables IDFA, IDFV, city, IP address and location tracking
await amplitude.setUserId(null); //forces autogeneration of random id
```

to regenerate a new random id if a different user logs in or out you can use 

```
await amplitude.regenerateDeviceId();
```

rest of the docs are here
https://developers.amplitude.com/docs/flutter-setup

**Comment by ricardobrg** [comment]
Still need to add this `await amplitude.regenerateDeviceId();` and the events. I will move it to  0.0.9 and move on from there.

**Comment by ricardobrg** [comment]
We need to define wich actions will be logged.

**Comment by ricardobrg** [comment]
track the sign in flow
