### ISSUE TITLE
Add a back button to the "go to inbox" page

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#5]
A user should have a back button to be able to go back to the login form page from the "go to inbox" page. For example, they may have misspelt their email address.

![Email](https://user-images.githubusercontent.com/3769672/113080258-9ecf9380-91a4-11eb-8d66-05c2f92dfba6.png)

**Comment by mike-audi** [comment]
waiting on design from @annastoilova. moving out of milestone

**Comment by annastoilova** [comment]
- Back button added. 

- Please display the email text so that the user can see which email they've entered.

![Inbox](https://user-images.githubusercontent.com/19438822/113950446-3f5b2e80-9809-11eb-8029-8aced85b242a.png)
