### ISSUE TITLE
When clicking the login email button some users get stuck

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#52]
Some users cannot get past the check your inbox screen. They do get the email and the email launches the app but they get stuck.

![image](https://user-images.githubusercontent.com/3769672/117182079-e8169280-ada3-11eb-9b10-7c7e38f88479.png)

Worth considering adding in the email a code they can copy paste into the app to manually login, in the event the link does not work. 

This issue is likely related to either the salt not being saved/persisted/deleted OR the user clicking an expired link

**Comment by mike-audi** [comment]
mike to followup with @bmgagnon

**Comment by mike-audi** [comment]
Steps to reproduce (has been reproduced on IOS)
1. install app on fresh 
2. enter email 
3. click login link in email 
4. on the backup keys screen click continue before doing any of the backup functions
5. you will be sent back to the login screen
6. you can request a new email link but you will not be able to get past the screen above


Fixes needed. 1) should not be able to click continue if you have not yet backed up your keys. 2) if you are logged out, you should still be able to log back in by requesting a new email

**Comment by ricardobrg** [comment]
Looks like it is solved.
- Continue is not clickable without saving the keys (#71).
- After the "save your keys" flow, user can login/logout.
