### ISSUE TITLE
On some phones the logout button is off screen

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#53]
Make the Home Screen a scroll view

![image](https://user-images.githubusercontent.com/3769672/117183925-201ed500-ada6-11eb-8e1c-045201b884d2.png)

**Comment by ricardobrg** [comment]
This is a broader then just the login screen... Other screens are getting this error too. The widget refactoring will solve this by wrapping the screens in scrollable widgets.

**Comment by ricardobrg** [comment]
It will be discussed in #58
