### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by BOC111** [tiki/app#561]
Testing this as a way to develop the app wireframes

1. Idea
2. Idea
3. Idea

![IMG_2047](https://user-images.githubusercontent.com/55149234/214649625-da369a8e-5911-47f8-a977-6619013cfa52.jpeg)

Does this image show?

**Comment by BOC111** [comment]
My thoughts are XYZ

**Comment by BOC111** [comment]
What about this?

![IMG_2046](https://user-images.githubusercontent.com/55149234/214650209-88a5db1a-2308-487f-94e7-d2b3c940c781.jpeg)

**Comment by mike-audi** [comment]
@BOC111 its a website bud. if you can see it, I can see it ;)
