### ISSUE TITLE
DAO App Voting section Edit & Replacement Text Section

### ISSUE THREAD

**Issue by BOC111** [tiki/app#565]
This is the section of the voting where a user can see the replacement text or the insertion of a new section into the rules & regulations.

**Comment by BOC111** [comment]
![IMG_2051](https://user-images.githubusercontent.com/55149234/215118927-f7c90fcc-14a8-4e35-b871-e6ab32b089b0.jpeg)
 This is the thinking on this section on 26/1

The up and down voting from the selection phase needs to be moved above the two text boxes.

**Comment by BOC111** [comment]
![IMG_2057](https://user-images.githubusercontent.com/55149234/215122387-0f67e90e-6482-4279-89fd-7f6132ac92fb.jpeg)
 Revised comparison section

**Comment by mike-audi** [comment]
approved. 

note: when we go to formally wireframe it, the selection phase section should either be a horizontal card or merged with the other status info at the top of the page.
