### ISSUE TITLE
Status subsection of Voting section the DAO App

### ISSUE THREAD

**Issue by BOC111** [tiki/app#566]
This is a key section in the voting section. This is where the user can see a snapshot of the current status of the proposal. 

It contains the following

1. Is the proposal going to pass?
2. Has the proposal reached quorum?
3. Has Tiki voted?
4. What is the impact of Tiki's vote?
5. What is the number of company votes and how have they influenced the vote?
6. What is the number of user votes and how have they influenced the vote?

This is the thinking as of 26/2
![IMG_2048](https://user-images.githubusercontent.com/55149234/215127152-3c771d17-994f-49e6-b4a8-63481dd60ee5.jpeg)

**Comment by BOC111** [comment]
I have reduced the text in the legends
I have stacked the overall status and the vote status
I have illustrated the impact of the Tiki vote.

@mike-audi Can you please take a look at this?

![IMG_2058](https://user-images.githubusercontent.com/55149234/215127618-5d813acc-15da-47e6-9990-851ad0949846.jpeg)

**Comment by mike-audi** [comment]
@BOC111 I don't understand the "Impact" chat, it seems to be the same as the two on the left.

**Comment by BOC111** [comment]
It is the same format (lollipop) as the two on the left/middle. Its purpose is to show the impact of the Tiki vote on quorum and pass/not pass.

**Comment by BOC111** [comment]
Edited image to simplify status view

![image](https://user-images.githubusercontent.com/55149234/216673983-b3dde54f-a8fa-4df1-8f4c-e82c28425bc1.jpeg)
