### ISSUE TITLE
Proposal Submission for DAO App

### ISSUE THREAD

**Issue by BOC111** [tiki/app#567]
There are 3 types of amendments to the rules and regulations for the operation of the TIKI DAO

1. Strike out words, sentences, or paragraphs
2. Insert (or add) words, sentences, or paragraphs
3. Strike out and insert (or substitute) words, sentences, or paragraphs

We will expand on the three types below in more detail.

_I have not used diagrams to illustrate these three edit features as they are mainly text-based and will be form based inputs._

**Comment by BOC111** [comment]
1. ### Strike out words, sentences, or paragraphs

If a user is looking to strike out words, sentences or paragraphs they will need to click **edit** 

This will bring them to a set of rules and regulations ( This a good example - https://foundation.wikimedia.org/wiki/Terms_of_Use/en)

The text will appear in a blue editable mode. 

The user will highlight any text that they wish to strike out.  The will click a button that says **Save Edit**

This will open a _New Proposa_l page.

The New Proposal page form will be pre-populated with the following-

1. A sequentially generated **TIP number**
2. The **date and time** of the edit
3. The authors **name**
4. The **Title** which will be "Edit section 12.6.1"
5. A **summary** of the change which will be the section with the text struck out with a red line.
6. A text box for the **reason for edit** to be completed by the proposer. This will be a max of 300 characters.
7. A proposed change will show the amended text ( rule & regulations)with the struck-out sections removed.
8. At the end of the form will be a **submit** button

**Comment by BOC111** [comment]
2. ### Insert (or add) words, sentences, or paragraphs

If a user is looking to add words, sentences or paragraphs they will need to click **edit** 

This will bring them to a set of rules and regulations ( This a good example - https://foundation.wikimedia.org/wiki/Terms_of_Use/en)

The text will appear in a blue editable mode. 

The user will highlight any point in the text where they wish to insert new text.  They will click a button that says **Save Edit**

This will open a _New Proposal_ page.

The New Proposal page form will be pre-populated with the following-

1. A sequentially generated **TIP number**
2. The **date and time** of the edit
3. The authors **name**
4. The **Title** which will be "Edit section 12.6.1"
5. A **summary** of the change which will be the section with the new text highlighted in yellow.
6. A text box for the **reason for edit** to be completed by the proposer. This will be a max of 300 characters.
7. A proposed change will show the amended text ( rule & regulations)with the new text inserted.
8. At the end of the form will be a **submit** button

**Comment by BOC111** [comment]
3. ### Strike out and insert (or substitute) words, sentences, or paragraphs

If a user is looking to strike out and add words, sentences or paragraphs they will need to click **edit** 

This will bring them to a set of rules and regulations ( This a good example - https://foundation.wikimedia.org/wiki/Terms_of_Use/en)

The text will appear in a blue editable mode. 

The user will highlight any point in the text where they wish to strike out and insert new text.  They will click a button that says **Save Edit**

This will open a _New Proposal_ page.

The New Proposal page form will be pre-populated with the following-

1. A sequentially generated **TIP number**
2. The **date and time** of the edit
3. The authors **name**
4. The **Title** which will be "Edit section 12.6.1"
5. A **summary** of the change which will be the section with the struck-out text highlighted in red and new text highlighted in yellow.
6. A text box for the **reason for edit** to be completed by the proposer. This will be a max of 300 characters.
7. A proposed change will show the amended text ( rule & regulations)with the struck-out sections removed and the new text inserted.
8. At the end of the form will be a **submit** button

**Comment by mike-audi** [comment]
I suggest simplifying this with 1 single workflow for all three. 

1. User clicks edit on the page (depending how we break up the guidelines)
2. User is shown the entire page in an editable doc form (kind of like google docs)
3. The user can make any changes they want (delete or add)
4. The user clicks done and a draft proposal is created which shows both the original and the proposed changes. Deletes are shown as red stike-thrus and adds are shown as yellow highlights 
5. The user enters their reason for the change and clicks submit

**Comment by BOC111** [comment]
**Editing or amending words, sentences, or paragraphs**

If a user is looking to strike out and add words, sentences or paragraphs they will need to click edit

This will bring them to a set of rules and regulations ( This a good example - https://foundation.wikimedia.org/wiki/Terms_of_Use/en)

The text will appear in editable mode, similar to a Word Doc.

The user will highlight any point in the text where they wish to strike out edit or insert new text. They will click a button that says Next.

This will open a _New Proposal_ page.

The New Proposal page form will be pre-populated with the following-

A sequentially generated TIP number
The date and time of the edit
The authors name
The Title will be "Edit section 12.6.1"
A summary of the change will be in the section with the struck-out or edited text highlighted in red and the new text highlighted in yellow.
A text box for the reason for the edit to be completed by the proposer. This will be a max of 300 characters.
A proposed change will show the amended text ( rule & regulations)with the struck-out or edited sections removed and the new text inserted.
At the end of the form will be a submit button.

![image](https://user-images.githubusercontent.com/55149234/216670995-d44154c2-f776-4e61-9e41-1546118db4f9.jpeg)
