### ISSUE TITLE
DAO User flow 

### ISSUE THREAD

**Issue by BOC111** [tiki/app#573]
The user flow for a user joining and using the DAO APP

**Comment by BOC111** [comment]
<img width="1161" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/218513760-09c7a919-d5d4-4835-ade3-e199959999ec.png">

**Comment by BOC111** [comment]
D2
<img width="1161" alt="Tiki DAO User Flow D2" src="https://user-images.githubusercontent.com/55149234/218514958-956e219d-f3b1-4391-a05b-bf17b2f722fa.png">

**Comment by BOC111** [comment]
<img width="1169" alt="Tiki DAO User Flow D3" src="https://user-images.githubusercontent.com/55149234/218746284-76ce15f2-5966-4102-a065-bc3775d0561f.png">

@mike-audi Can. you look at the issues in yellow. These are the things that need your clarification

**Comment by mike-audi** [comment]
no password - we don't do passwords, login is handled via magic links (email)

automatic - yes, on signup a wallet is auto-created

not only do we not use cookies, but they are not a thing in mobile apps.

I'd recommend sticking to app only notifications to start and pick a single notification frequency, tho most typically these are asynchronous.

**Comment by BOC111** [comment]
Ok, thanks

**Comment by BOC111** [comment]
So, there is no browser access at all?

**Comment by BOC111** [comment]
<img width="1169" alt="Tiki DAO User Flow D4" src="https://user-images.githubusercontent.com/55149234/218790626-528e10d0-b70f-40e9-b538-76d34cfa9074.png">

 @mike-audi I want to give the user an option to receive email updates in addition to in-app.

**Comment by BOC111** [comment]
<img width="1391" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/219646654-a8a2df48-90f8-4f70-b3e7-3f7fffcc2535.png">

**Comment by mike-audi** [comment]
- intro section is unnecessary; remove it.
- remove adjustable frequency from asynchronous updates
- login happens before wallet account creation
- login is missing the email magic link/one-time password login flow
- I don't understand the 2 parts under proposals for submission, but if one of those is editing the R&R, that belongs under "Read"
- "Read" needs a different name, since it's not just read -> its view and modify the current R&R
- Why is community its own screen/tab? & how is community different from comments?
- this is missing the requirements around referral codes & special links for companies to sign up

**Comment by BOC111** [comment]
@mike-audi 

**Intro section is unnecessary; remove it.**
Why? How else will we know if a new user has been introduced by a "friend" or a company when they don't have a code?


<img width="1445" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/220323602-487aa0e4-dc1b-4e0d-a19c-70ced7460574.png">

**Comment by mike-audi** [comment]
referral codes are embedded in the link used to install the app -> the same way we know if its an authorized company rep or a user.

**Comment by BOC111** [comment]
<img width="1662" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/221677232-9a9a1898-dbb6-4450-a871-803bfb340849.png">

**Comment by mike-audi** [comment]
1. Add to origination: A user clicks a referral link
2. Remove "stay logged in" option (not a thing for mobile apps)
3. Move optional account and update settings downstream to an account block post-login (combine logout with this)
4. Remove userId populated in form from login flow (it's automatically handled)
5. You don't read the rules & regs on GitHub, only in the app

**Comment by BOC111** [comment]
<img width="1374" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/223512763-ed8f6e8a-21e0-474a-8883-d7d18596128e.png">

**Comment by mike-audi** [comment]
discord & updates move to post login
logout moves to post login
post login moves to the end and renamed to settings 
remove identity from account creation.

**Comment by BOC111** [comment]
<img width="1374" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/224366196-b2e0217f-75df-4724-a3b3-cf0df7ca7645.png">

**Comment by BOC111** [comment]
<img width="1374" alt="Tiki DAO User Flow" src="https://user-images.githubusercontent.com/55149234/225899983-b5597f49-b4c1-41b8-9962-b34afedec5c1.png">
