### ISSUE TITLE
Payment & Performance - Buyer Guidelines

### ISSUE THREAD

**Issue by BOC111** [tiki/app#588]
The Payment & Perfromance subsection of Data Buyer Guidelines https://github.com/tiki-bar/app/issues/582

Purpose
The payment and performance guidelines that a company or company user will read or refer to for their engagement with the data.

Intent
To be read by a data buyer or developer to understand how to engage/interact with the data.

Completion
A set of guidelines suitable for a "professional".

Note
This does not include the legal policy documents for privacy and data access.

**Comment by BOC111** [comment]
1. The consideration or compensation for access to the user’s data is an agreement between the company and the user. Tiki is not part of that agreement. 
2. This payment may not be monetary, but can be a discount, or credit against future purchases or services. 
3. To make it easier for the user to understand a payment cycle, we suggest that the payment cycle is 30 days. This is easier to monitor by both parties. XX
4. If a company fails to make the payment or breaches the agreement with the user, the user can inform Tiki, and the company may be suspended or even removed from the system.
5. 
6. So that the user understands the offer that you are making for access to the data, the offer should be very clear and precise. For example, “If you give us access to you xxxx data we will give you xxxx for every 30 days that we have access.”
7. The agreement between you and the user is a contract and is subject to a consumer contract's usual terms and conditions. Therefore, you must ensure that the contents of their standard terms and conditions for consumers and any other users comply with all applicable consumer laws.
8. A breach is when one of the two parties actively breaks or fails to fulfil the agreed-upon terms. This may be for things like payment or performance. It is a violation of the terms that both parties agreed to by one of the parties. 
9. When one or both parties inform Tiki of a legitimate breach of an agreement, one or both parties may be suspended from the service.

**Comment by mike-audi** [comment]
Comp guidelines we need are:

- if you offer comp for data, you need to include but not limited to:
  - billing cycle/ net 15, 30, 45 etc.
  - remediation for a mid-cycle opt-out (users can change their mind at any time)
  - explicitly define the payment form
  - limited liability clause
  - dispute resolution clause -> tho this may better fit somewhere else.

**Comment by BOC111** [comment]
1. The payment or compensation for access to the user’s data is an agreement between the company and the user. Tiki is not part of that agreement.
2. The payment is something that you agree with the user with an offer in exchange for access to their data. This payment may or may not be monetary but can be a discount on goods or services, or credit against future purchases or services. 
3. To make it easier for the user to understand a payment cycle, we suggest that you agree on the payment in your offer to the user. 
4. We would suggest that the payment or billing cycle where you pay or reward the user is in a cycle of 15, 30 or 45 days. This is easier to monitor by both parties.
5. If a company fails to make the payment or breaches the agreement with the user, the user can inform Tiki, and the company may be suspended or even removed from the system. If there is a dispute that cannot be easily reconciled, we would refer you to the _[Redress](https://github.com/tiki-bar/app/issues/589#issue-1615426687) page._
6. So that the user understands the offer that you are making for access to the data, the offer should be very clear and precise. For example, “If you give us access to your xxxx data we will give you xxxx for every 30 days that we have access.”
7. The agreement between you and the user is a contract and is subject to a consumer contract's usual terms and conditions. Therefore, you must ensure that the contents of their standard terms and conditions for consumers and any other users comply with all applicable consumer laws.
8. A breach is when one of the two parties actively breaks or fails to fulfil the agreed-upon terms. This may be for things like payment or performance. It is a violation of the terms that both parties agreed to by one of the parties.
9. When one or both parties inform Tiki of a legitimate breach of an agreement, one or both parties may be suspended from the service but only after both parties have attempted to find a solution as per _[Redress](https://github.com/tiki-bar/app/issues/589#issue-1615426687) page._

**Comment by mike-audi** [comment]
moved into #590
