### ISSUE TITLE
Redress - Buyer Guidelines

### ISSUE THREAD

**Issue by BOC111** [tiki/app#589]
### Redress

Most buyer or company concerns can be resolved by use of our Tiki support site at https://support.mytiki.com/. If Tiki is unable to resolve your concerns and a dispute remains between you and a user or you and Tiki this Section explains how the parties have agreed to resolve it.

A.	**Must Arbitrate All Claims Except Intellectual Property, Unauthorized Use, Piracy, or Theft**

YOU AND THE USER AGREE TO RESOLVE ALL DISPUTES AND CLAIMS BETWEEN EACH OTHER IN INDIVIDUAL BINDING ARBITRATION. THAT INCLUDES BUT IS NOT LIMITED TO, ANY CLAIMS ARISING OUT OF OR RELATING TO: (i) ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU AND THE USER(S); (ii) THIS AGREEMENT; OR (iii) YOUR USE OF TIKI, YOUR ACCOUNT, HARDWARE OR THE CONTENT AND SERVICES. IT APPLIES REGARDLESS OF WHETHER SUCH CLAIMS ARE BASED IN CONTRACT, TORT, STATUTE, FRAUD, UNFAIR COMPETITION, MISREPRESENTATION OR ANY OTHER LEGAL THEORY, AND INCLUDES ALL CLAIMS BROUGHT ON BEHALF OF ANOTHER PARTY.

However, this does not apply to the following types of claims or disputes, which you or Tiki may bring in any court with jurisdiction: (i) claims of infringement or other misuses of intellectual property rights, including such claims seeking injunctive relief; and (ii) claims related to or arising from any alleged unauthorized use, piracy, or theft.

This does not prevent you from bringing your dispute to the attention of any federal, state, or local government agencies that can, if the law allows, seek relief from us for you.

An arbitration is a proceeding before a neutral arbitrator, instead of before a judge or jury. Arbitration is less formal than a lawsuit in court, and provides more limited discovery. It follows different rules than court proceedings, and is subject to very limited review by courts. The arbitrator will issue a written decision and provide a statement of reasons if requested by either party. YOU UNDERSTAND THAT YOU AND THE USER(s) ARE GIVING UP THE RIGHT TO SUE IN COURT AND TO HAVE A TRIAL BEFORE A JUDGE OR JURY.

B. **Try to Resolve Dispute Informally First**

You and the User(s) agree to make reasonable, good-faith efforts to informally resolve any dispute before initiating arbitration. A party who intends to seek arbitration must first send the other a written notice that describes the nature and basis of the claim or dispute and sets forth the relief sought. If you and the User(s) do not reach an agreement to resolve that claim or dispute within thirty (30) calendar days after the notice is received, you or the User(s) may commence an arbitration. Written notice to Tiki must be sent via postal mail to: ATTN: Arbitration Notice, Tiki Corporation, 1814 Hayes St, Nashville, TN 37203.

C. **Arbitration Rules and Fees**

The U.S. Federal Arbitration Act applies to this section as far as your country’s laws permit. The arbitration will be governed by the Consumer Arbitration Rules (or the Commercial Arbitration Rules, if the Consumer Arbitration rules are inapplicable) of the American Arbitration Association ("AAA") as modified by this Agreement. Rules are available at http://www.adr.org. The arbitrator is bound by the terms of this Agreement.

The AAA will administer the arbitration. Outside the U.S., Tiki will recommend a neutral arbitration provider that uses these or similar rules. It may be conducted through the submission of documents, by phone, or in person in the country where you live or at another mutually agreed location.

If you seek $10,000 or less, Tiki agrees to promptly reimburse your filing fee and your share if any of AAA’s arbitration costs, including arbitrator compensation, unless the arbitrator determines your claims are frivolous or were filed for harassment. Tiki agrees not to seek its attorneys’ fees or costs unless the arbitrator determines your claims are frivolous or were filed for harassment. If you seek more than $10,000 and the AAA Consumer Arbitration Rules do not apply, the AAA’s arbitration costs, including arbitrator compensation, will be split between you and Valve according to the AAA Commercial Arbitration Rules.

D. **Individual Binding Arbitration Only**

YOU AND THE USER(S) AGREE NOT TO BRING OR PARTICIPATE IN A CLASS OR REPRESENTATIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, WHISTLE BLOWER ACTION, OR CLASS, COLLECTIVE, OR REPRESENTATIVE ARBITRATION, EVEN IF AAA’s RULES WOULD OTHERWISE ALLOW ONE. THE ARBITRATOR MAY AWARD RELIEF ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT OF THAT PARTY’S INDIVIDUAL CLAIM. You and Valve also agree not to seek to combine any action or arbitration with any other action or arbitration without the consent of all parties to this Agreement and all other actions or arbitrations.

This Agreement does not permit class, collective, or representative arbitration. A court has exclusive authority to rule on any assertion that it makes.

E. What Happens if Part of Section 11 Is Found Illegal or Unenforceable

If any part of the above (Dispute Resolution/Binding Arbitration/Class Action Waiver) is found to be illegal or unenforceable, the rest will remain in effect (with an arbitration award issued before any court proceeding begins), except that if a finding of partial illegality or unenforceability would allow class, collective, or representative arbitration, all of the above will be unenforceable and the claim or dispute will be resolved in court.

F. **Miscellaneous**

Except as otherwise expressly set forth in this Agreement, in the event that any provision of this Agreement shall be held by an arbitrator, court, or another tribunal of competent jurisdiction to be illegal or unenforceable, such provision will be enforced to the maximum extent permissible and the remaining portions of this Agreement shall remain in full force and effect. This Agreement, including any Payment Terms, Rules of Use, and the TIKI Privacy Policy constitutes and contains the entire agreement between the parties with respect to the subject matter hereof and supersedes any prior oral or written agreements. You agree that this Agreement is not intended to confer and does not confer any rights or remedies upon any person other than the parties to this Agreement.

Tiki’s obligations are subject to existing laws and legal processes and Tiki may comply with law enforcement or regulatory requests or requirements notwithstanding any contrary term.

You agree to comply with all applicable import/export laws and regulations. You agree not to export the content or data or allow the use of your Account by individuals of any terrorist-supporting countries to which encryption exports are at the time of exportation restricted by the U.S. Bureau of Export Administration. You represent and warrant that you are not located in, under the control of, or a national or resident of any such prohibited country.

The U.S. Federal Arbitration Act applies to this Section 11 as far as your country’s laws permit. The arbitration will be governed by the Consumer Arbitration Rules (or the Commercial Arbitration Rules, if the Consumer Arbitration Rules are inapplicable) of the American Arbitration Association ("AAA") as modified by this Agreement. Rules are available at http://www.adr.org. The arbitrator is bound by the terms of this Agreement.

The AAA will administer the arbitration. Outside the U.S., Tiki will select a neutral arbitration provider that uses these or similar rules. It may be conducted through the submission of documents, by phone, or in person in the country where you live or at another mutually agreed location.

If you seek $10,000 or less, Tiki agrees to promptly reimburse your filing fee and your share if any of AAA’s arbitration costs, including arbitrator compensation, unless the arbitrator determines your claims are frivolous or were filed for harassment. Tiki agrees not to seek its attorneys’ fees or costs unless the arbitrator determines your claims are frivolous or were filed for harassment. If you seek more than $10,000 and the AAA Consumer Arbitration Rules do not apply, the AAA’s arbitration costs, including arbitrator compensation, will be split between you and Tiki according to the AAA Commercial Arbitration Rules.

This Agreement does not permit class, collective, or representative arbitration. A court has exclusive authority to rule on any assertion that it does.

**Comment by mike-audi** [comment]
moved into #590
