### ISSUE TITLE
Data Buyer Guidelines

### ISSUE THREAD

**Issue by BOC111** [tiki/app#590]
**The Buyer Guidelines.**

Purpose
The guidelines that a company or company user will read or refer to for their engagement with the data licencing process.

Intent
To be read by a data buyer or developer to understand how to engage/interact with the data licensing process.

Completion
A set of guidelines suitable for a "professional".

Note
This does not include the legal policy documents for privacy and data access.

**Comment by BOC111** [comment]
The agreement between a data seller and a data licencor is called a User Data Licencing agreement or UDLA. This guideline sets out the guidelines for a buyer or licencor when creating a UDLA. There are some mandatory requirements for the UDLA set out in this guideline, these requirements need to be included in every UDLA or it will be an invalid offer.

1.	**Compensation**- The company or licencor offers the user (licencee) compensation in exchange for a licence to access to their data. The compensation or payment is something agreed with the user/licenccee with an offer in exchange for a licence for their data. This payment may or may not be monetary or can be a discount on goods or services or credit against future purchases or services. The company or licencor of the data must define the compensation offered to the user/licancee in very clear terms. So that the user/licencee understands the offer that you, the licancor is making for a licence to use the data, the offer should be very clear and precise. For example, "_If you give us access to your xxxx data, we will give you xxxx for every 30 days that we have access”_. In some cases, there is no compensation or payment, but this must be explicit in the offer. 
  i. You, the licencor must clearly state the offer and nature of compensation or lack there thereof,  in the User Data Licence Agreement (UDLA). 
  ii. Any and all criteria required for compensation must be clearly stated in the UDLA.

2.	**UDLA Duration**- The data licence or UDLA will be agreed between the licencor and licencee. As part ofthe UDLA the duration of the agreement will be explictliy agreed and must be clear and easy for the user to usderstand. The UDLA is a perpetual agreement by nature but will need a clearly defined renewal process whre the licencor is agreeing to the renewal in an auidiatable way.  
  i. All UDLAs are perpetual in nature but will need renewal at an agreed interval.
  ii. All UDLAs agreements will need to be explict and have a renewal term.
  iii. All UDLAs will need an auditable form of agreement from the licencee.
  ii. If either side decides to terminate the UDLA 30 days notice must be provided.
  
1.	**Define the data**- The data you (the licencor) request or offer to licence must be clearly defined and easy for the user to understand. The offer must be explicit and precisely state what data you want to licence. This could be email data, social media data etc. The user/licanecee must understand that the data they will licence is only the agreed data and nothing else. 
  i. The UDLA must clearly state the data that the licancor is seeking to licence from the licancee in terms that they will easily understand.

3.	**The user/licencee must be the legal owner** – The user/licancee that is the recipient of a UDLA offer must be the legal owner of the data. Only a legal owner has the power to issue a licence or grant permission for use. If the user/licancee is on a company-issued device or a third party is paying for the mobile contract, the user may not be the legal owner of the data on the device. The data may be subject to regulatory or legal constraints in some heavily regulated industries. In less regulated industries, the data may be subject to a confidentiality agreement that the employee signed with the company that issued the device. 
  i. You can only enter into a UDLA with the legal owner of the device.

5.	**Minors Data** -As a company/licancor and a user/licencee, you must comply with applicable privacy laws around the world relating to the collection of data from children online. In addition, data from minors or children may not include personally identifiable information or device information from third parties. 
  i. The UDLA will be subject to the local laws relating to the privacy of minors.
  ii. Only a licancee that has reached the age of concent can agree to a UDLA.

7.	**Laws around the world** - The agreement between you and the user is a contract and is subject to a consumer contract's usual terms and conditions. So, you will need to make sure that the contents of their standard terms and conditions for consumers and any other users comply with all applicable and relevant consumer laws.
  i. You must comply with all local consumer legislation in your jurisdiction.
  ii. All UDLAs will be subject to the relevant consumer legislation.

9.	**Arbitration clause**- Most buyer or company concerns can be resolved by use of our Tiki support site at https://support.mytiki.com/. If Tiki is unable to resolve your concerns and a dispute remains between you and a user or you and Tiki, you agree to resolve the dispute through arbitration. You and the user agree to resolve all disputes and claims between each other in individual binding arbitration. That includes but is not limited to any claims arising out of or relating to (1) any aspect of your relationship between you and the users. (2) This agreement. (3) Your use of the Tiki platform or services. This applies whether such claims are based in contract, tort, statute, fraud, unfair competition, misrepresentation or any other legal theory and includes all claims brought on behalf of another party. Add a clause in every UDLA - Indemnify TIKI - remove step 1
  i. The first step in problem resolution is @support.mytiki.com
  ii. The second step is by seeking arbitration for both parties.

11.	**Definition of Acceptance** – As part of the agreement between you and a user, the user must communicate their acceptance of the terms of the offer. Simply making an offer to a user is insufficient; the user must agree and communicate that agreement. The acceptance can be in a tick box or button to indicate acceptance of the terms offered. There must be auditable proof of acceptance, or the agreement will remain an offer, and no data will be licenced from that user.
  i. You must have an explicit record of acceptance for your offer from the user. out -must be explicit in the UDLA.

12.	**Opt-out**- As part of your UDLA UI, there will be the option for the user to opt out. The user has the right to opt out of the agreement at any time. If the user opts out any credits owed from the UDLA must be settled as possible. Any discounts or future promises for data licences are invalid on cancellation or opt-out by the user. 
  i. You must give the user the ability to opt out at any time.
  ii. On termination all credits must be paid or transferred as soon as practically possible. **Explain termination** must be explained in UDLA
      must be reasonable

15.	**Data use**- As part of the offer to a user you must explain to the user what you intend to use the data for. The user is going to be far more likely to accept your offer to licence their data if they understand what you intend to do with their data. It is up to you to explain to the user what your intentions are for their data. 
  i. The UDLA offer must contain some information about how you intend to use the data.

**Comment by mike-audi** [comment]
notes for discussion:

- 

- [x] expiry: no defaults on contract duration or renewal. if no duration is listed, its assumed to be perpetual. (all contracts are at-will, since the user can opt-out at any point).
- [x] - defining the data section should include the data use section.
- [x] - under the ownership section, it should be clear the user is not transferring ownership just a license
- [x] - the minor's section is not about collection of minor's data per say, while yes, that must also follow all local laws, the bigger issue is the agreeing to a legal contract with a minor (they do not have the authority to sign off on it). 
- [x] - under laws, I don't understand the difference between i & ii.
- [x] - the arbitration language needs to be changed entirely. they have to put in the contract a dispute resolution clause, that indemnifies TIKI. 
- [x] - under acceptance, tiki auto-records the acceptance, so we need to rephrase the language. the key requirement here is that a user must explicitly opt-in. 
- [x] - under opt-out, ii & iii are both incorrect. we do not set the opt-out terms, we simply require them to be set.

**Comment by BOC111** [comment]
The agreement between a data seller and a data licensor is called a User Data Licencing agreement or UDLA. This guideline sets out the guidelines for a buyer or licensor when creating a UDLA. There are some mandatory requirements for the UDLA set out in this guideline, these requirements need to be included in every UDLA, or it will be an invalid offer. The user or licensor will grant a licence to a company or licensee from the user for a defined set of data. The company or licensee will be permitted to use the data outlined in the UDLA for an agreed form of compensation.

1.	**Compensation**- The company or licensor offers the user (licensee) compensation in exchange for a licence to access their data. The compensation or payment is something agreed with the user/licensee with an offer in exchange for a licence for their data. This payment may or may not be monetary or can be a discount on goods or services or credit against future purchases or services. The user/licensor or licensor of the data must define the compensation offered to the user/licensee in very clear terms. So that the user/licensee understands the offer that you, the licensor, are making for a licence to use the data, the offer should be very clear and precise. For example, "If you give us access to your xxxx data, we will give you xxxx for every 30 days that we have access”. In some cases, there is no compensation or payment, but this must be explicit in the offer.
  i. _**You, the licensor must clearly state the offer and nature of compensation, or lack thereof, in the User Data Licence Agreement (UDLA).
  ii. THe licence must include a duration and will be renewed with a new licence at the end of that period. 
  iii. any changes to the compensation will require a new agreement to repalce the origional one. **_

2.	**UDLA Duration**- The data licence or UDLA will be agreed upon between the licensor and licensee. As part of the UDLA the duration of the agreement will be explicitly agreed upon and must be clear and easy for the user/licensee to understand. The UDLA is a perpetual agreement by nature but will need a clearly defined renewal process where the licensor is agreeing to the renewal in an auditable way.
  i. _**The duration or lifetime of all UDLAs must be defined, if not it is assumed to be a perpetual agreement.
  ii. All UDLAs are perpetual but will require renewal at an agreed interval.  
  iii. The renewal process must be explicit in the UDLA.
  iv. The renewal must be on reasonable terms for both the licensor and licensee.**_

3.	**Define the data to be licenced**- The data you (the licensor) request or offer to licence must be clearly defined and easy for the user/licensee to understand. The offer must explicitly state what data you wish to licence. This could be email data, social media data etc. The user/licensee must understand that the data they will licence is only the agreed data and nothing else.
  i. **_The UDLA must clearly state the data that the licensor is seeking to licence from the licensee in terms they will easily understand.
  ii. The licence msut alss include the following
  iii. **The use case for the data** - this is writen in terms that the user will understand.
  iv. **The data usage** - the is the data tags of the data being used in the licence.
  v. **The data destination** - this is the destination of the data. This amy be for internal storage or an extenal data lake or warhouse.
  iv. **The frequency of the query** - this is the frequency of the data extraction. _**

4.	**The user/licensee must be the legal owner** – The user/licensee who receives a UDLA offer must be the legal ownerquency of the  of the data. Only a legal owner can issue a licence or grant permission to use the data. If the user/licensee is on a company-issued device or a third party is paying for the mobile contract, the user/licensee may not be the legal owner of the data on the device. The data may be subject to regulatory or legal constraints in some heavily regulated industries. In less regulated industries, the data may be subject to a confidentiality agreement that the employee signed with the company that issued the device.
  i. **_You can only enter into a UDLA with the legal owner of the data._**

5.	**Minors Data** -As a company/licensor and a user/licensee, you must comply with applicable privacy laws around the world relating to the collection of data from children online. In addition, data from minors or children may not include personally identifiable information or device information from third parties.
  i. **_The UDLA will be subject to the local laws relating to the privacy of minors.
  ii. Only a licensee that has reached the age of consent in the jurisdiction  of the UDLA can agree to a UDLA._**

6.	**Laws around the world** - The agreement between you and the user/licensee is a contract and is subject to a consumer contract's usual terms and conditions. So, you will need to make sure that the contents of their standard terms and conditions for consumers and any other user/licensees comply with all applicable and relevant consumer laws.
  i. **_All UDLAs must comply with all local consumer and relevant legislation in your jurisdiction._**

7.	**Dispute resolution**- Most simple licensor queries or concerns can be resolved using the Tiki support site at https://support.mytiki.com/. If Tiki cannot resolve the concerns or queries and a dispute arises between the licensor and a licensee or either party, all parties must agree to resolve the dispute through arbitration. The licensor and the licensee agree to resolve all disputes and claims between each other in individual binding arbitration. The UDLA must include a clause that sets this out explicitly. The clause should include but is not limited to any claims arising out of or relating to (1) any aspect of your relationship between you and the user/licensees. (2) This agreement. (3) Your use of the Tiki platform or services. This applies whether such claims are based in contract, tort, statute, fraud, unfair competition, misrepresentation or any other legal theory and includes all claims brought on behalf of another party. 
  i. **_The UDLA must include a clause that expressly states that both parties will agree to dispute resolution in the case of a dispute. 
  ii. This clause will indemnify Tiki Inc. and all employees in a dispute between the licensor and licensee._**

8.	**Definition of Acceptance** – As part of the UDLA agreement between you, the licensor and a user/licensee, the licensee must communicate their acceptance of the terms of the offer. The acceptance can be in a tick box or button to indicate acceptance of the terms offered. There must be an explicit form of acceptance, or the agreement will remain an offer, and no data will be licenced from that user/licensee.
  i. **_You, the licensor must have an explicit record of acceptance of your offer from the licensee._** 

9.	**Opt-out**- As with most agreements, it is possible for both parties to decide to opt out of the agreement. The licensor can withdraw the payment or consideration for the UDLA with a reasonable notice period. This notice period needs to be included in the ULDA. The licensee can withdraw their licence at any time. The effect of either of these actions will have the effect of voiding the UDLA. If the user/licensee opts out, credits owed from the UDLA should be settled as possible. Any discounts or future promises for data licences are invalid on cancellation or opt-out by the user/licensee.
  i. **_The licensee can opt out of a UDLA at any time and without notice.
  ii. The definition of the process of opt-out by both parties must be included in the UDLA.
  iii. Every UDLA must include a definition of how the opt-out will affect the termination of the agreement and the associated actions.
  iv. The notice period that the licensor provides to the licensee will be clearly defined in the UDLA._** 

10.	**Data use**- As part of the offer to a user/licensee, you, the licensor, must explain to the user/licensee what you intend to use the data for. The user/licensee will be far more likely to accept your offer to licence their data if they understand what you intend to do with their licenced data. It is up to you to explain to the user/licensee your intentions for their licenced data. 
  i. **_The UDLA offer must contain a definition of how you intend to use the data._**

13. **Superceeding agreements** - Every UDLA will be required to include the following clause -
   i.**_This Agreement (UDLA)supersedes any and all prior agreements (UDLA) between the parties with respect to the subject matter hereof._**

**Comment by BOC111** [comment]
The agreement between a data seller (the user) and a data licensor (the company) is called a User Data Licencing agreement or UDLA. This guide sets out the guidelines and hopefully answers any questions for a buyer or licensor (company) when creating a UDLA. 

First off, let's establish the names and roles
  i. The licensor or "seller" of the data is the **user**.
  ii. The licensee or "buyer" of the data is the **Company** (you).

The basis of the agreement is a two-way exchange. The user will grant a licence to a company from the user for a defined set of data. The company will be permitted to use the data outlined in the UDLA for an agreed form of compensation.

There are some mandatory requirements for the UDLA set out in this guideline, these requirements need to be included in every UDLA, or it will be an invalid offer.

### Data permissions
This is the core of the UDLA and sets out the permission from the user to where they agree to share information with you, the company and selected third parties. It also includes a statement that the UDLA will have no impact on the existing or future commercial relationships based on the user buying goods or services from the company. This means that if the UDLA doesn't work out it should not impact their prior commercial relationship.

### Data uses
This sets out to establish that the company will not use the data specified in _3. Data Uses_ for any other purpose than the purposes set out in the Data Use table. This should give some reassurance to the user that the data will not be used for anything other than the agreed purposes. 

### Data usage
As a company, the data request or offer to licence must be clearly defined and easy for the user/licensee to understand. The offer must explicitly state what data you wish to licence and what you intend to do with it. The user should understand that the data they will licence is only the agreed data and nothing else.
  **i. _The UDLA must clearly state the data that the licensor is seeking to licence from the licensee in terms they will easily understand.
  ii. The licence must also include the following
  iii. The use case for the data - this is written in terms that the user will understand.
  iv. The data usage - are the data tags/terms of the data being used in the licence.
  v. The data destination - this is the destination of the data. This may be for internal storage or an external data lake or warehouse but the location must be shared.
  iv. The frequency of the query - this is the frequency of the data extraction. _**

### Compensation
The company offers the user compensation in exchange for a licence to access their data. The compensation or payment is something agreed upon with the user by an offer in exchange for a licence for their data. This payment/reward may or may not be monetary or can be a discount on goods or services or credit against future purchases or services. Or, some other compensation that the user thinks is a fair price. The company making the offer must define the compensation offered to the user in very clear terms. To ensure that the user understands the offer you are making for a licence to use the data, the offer should be very clear and precise. For example, "_If you give us access to your xxxx data, we will give you xxxx for every 30 days that we have access_”. In some cases, there may be no compensation or payment, but this must be explicit in the offer.
  **i. You, the company must clearly state the offer and nature of compensation, or lack thereof, in the User Data Licence Agreement (UDLA).
  ii. The licence must include a duration and will be renewed with a new licence at the end of that period.
  iii. any changes to the compensation will require a new agreement to replace the original one (see Alteration below).**

### Privacy and confidentiality
This is a privacy statement that sets out your undertakings to endeavour to maintain the confidentially of the user and their data. 

### Duration
The UDLA is perpetual in nature with a renewal every twelve months. The date of origin for the UDLA will be the date the user communicates their acceptance of the offer. This date of origination will be one of the essential terms of the UDLA.
  **i. The data of acceptance is the start date of the agreement.**

### Alteration
The terms for alteration are very simple and explicit, any changes or alterations to the UDLA render it void. If you wish to make any alterations to the UDLA, you must issue a new offer to the user that will contain the amended terms.
  **i. A new UDLA must be offered to the user in the event of any alterations or amendments to the UDLA.**

### Governing law
The governing jurisdiction for the UDLA will be the jurisdiction where you are located or the location of your registered office.
  **i. The full address of your location or registered office must be entered into the UDLA**.

### Opt-out
As with most agreements, it is possible for both parties to decide to opt out of the agreement. The company can withdraw the payment or consideration for the UDLA with a reasonable notice period. This notice period needs to be included in the ULDA. The user can withdraw their licence at any time. The effect of either of these actions will have the effect of voiding the UDLA. If the user opts out, credits owed from the UDLA should be settled as possible. Any discounts or future promises for data licences are invalid on cancellation or opt-out by the user.
  **i. The company can opt out of a UDLA at any time and without notice.
  ii. The definition of the process of opt-out by both parties must be included in the UDLA.
  iii. Every UDLA must include a definition of how the opt-out will affect the termination of the agreement and the associated actions.
  iv. The notice period that the company provides to the user will be clearly defined in the UDLA.**

### You the licensee agree that 
The user has obligations on acceptance of the UDLA. The user must be legally capable of sharing data and cannot share data that is contractually or legally restricted. This may be data that is subject to an employment contract or a federal employee or if they are underage. 

### Limitation of liability
This is a statement that limits the liability of both parties to the UDLA in the event of a dispute or breach of the agreement.

### Third-party indemnity
Tiki Inc. is the originator of the UDLA and will be the facilitator of an agreement but is not a party to the agreement and as such is not liable to either party for the contents or performance of the UDLA.
