### ISSUE TITLE
Add a resend email button to the go-to inbox page

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#6]
Add a button to resend the email if the user did not receive it to the go-to inbox page. Potentially also add the email address the email was sent to. Users may misspell their email address and never receive it. 

![Email](https://user-images.githubusercontent.com/3769672/113080441-f0781e00-91a4-11eb-9a7b-ed0652fc5f70.png)

**Comment by mike-audi** [comment]
waiting on design from @annastoilova. moving to later milestone

**Comment by annastoilova** [comment]
![Inbox](https://user-images.githubusercontent.com/19438822/113950560-8cd79b80-9809-11eb-8f88-0cc3169e9b00.png)
