### ISSUE TITLE
Link Gmail account

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#75]
## Problem statement
Users need a way to link their Gmail account so that they can see what data is held by Gmail, start controlling that data, or lat4er on monetize such data.

## Proposed work
Add the ability for the user to link their Gmail account by logging into their Gmail account in-app, with their app credentials.

Roadmap ticket: https://www.notion.so/mytiki/Link-Gmail-account-9fcff4e017f44cfbb238e1a5b128b201

**Comment by ricardobrg** [comment]
Using the google_sign_in package to handle that. Working on UI.

**Comment by ricardobrg** [comment]
I will leave that open and tracking the background process while #89 will be the UI layer of it.
