### ISSUE TITLE
Unsubscribe from SPAM

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#77]
## Problem statement
Users don't have the ability to easily unsubscribe from SPAM emails

## Proposed work
A feature within the TIKI app that allows users to easily unsubscribe from SPAM within a click of a button

Roadmap ticket link w/ user stories: https://www.notion.so/mytiki/Unsubscribe-from-SPAM-1f177a0ea0ea4d4e8ddc8a766ee50731

**Comment by ricardobrg** [comment]
This will probably be broken in smaller features. Just moving to 0.1.1 for now.
