### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#9]
Critical to have good test automation for a CI/CD (#1) pipeline

**Comment by mike-audi** [comment]
removing from milestone 0.0.2. pipeline works without automated testing at the moment. will move to later release

**Comment by ricardobrg** [comment]
In 0.0.9 we need to add unit, widget and e2e tests.

- Any new feature needs at least 80% coverage, but the goal is always 100%.
- Every issue needs a e2e acceptance test.

TBD the standards for testing and verification.

**Comment by ricardobrg** [comment]
Moved to 0.1.0 to complete implementation.

**Comment by ricardobrg** [comment]
moving it to 0.1.1, because it will be in the new CI/CD flow for testing

**Comment by ricardobrg** [comment]
Closing this now because it is too broad to exist as an issue by itself because it is an ongoing process. This should be a policy defined in #307 and followed in every commit.
