### ISSUE TITLE
Email login flow breaks after clearing app data

### ISSUE THREAD

**Issue by mike-audi** [tiki/app#97]
Steps to reproduce on Android:
1. log in
2. clear app data 
3. type your email 
4. open log in link
3. you get logged out

**Comment by ricardobrg** [comment]
It happens because the email is stored in secure storage during the otp login. Em 24 de mai de 2021 13:29, Mike Audi ***@***.***> escreveu:
Steps to reproduce on Android:
log inclear app datatype your emailopen log in linkyou get logged out

**Comment by mike-audi** [comment]
it should still be able to log you in. once you clear the app data, you should get logged out. then when you try and log back log back in it should work.

**Comment by ricardobrg** [comment]
#175
